### ISSUE TITLE
Error: method:createLogStream is not on whitelist

### ISSUE THREAD

**Issue by sdgathman** [evbogue/minbay#2]
This could be a documentation issue - the permissions are configured somehow, but I don't know how.  I obtained a modern invite from scuttlebot, and imported my key.  But minbay won't display anything, showing this error instead:
```
Error: method:createLogStream is not on whitelist
    at Function.perms.pre (/home/stuart/src/scuttlebot/node_modules/muxrpc/permissions.js:88:14)
    at Object.<anonymous> (/home/stuart/src/scuttlebot/node_modules/muxrpc/local-api.js:35:21)
    at PacketStreamSubstream.stream.read (/home/stuart/src/scuttlebot/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/home/stuart/src/scuttlebot/node_modules/packet-stream/index.js:230:11)
    at PacketStream.write (/home/stuart/src/scuttlebot/node_modules/packet-stream/index.js:135:41)
    at /home/stuart/src/scuttlebot/node_modules/muxrpc/pull-weird.js:56:15
    at /home/stuart/src/scuttlebot/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/stuart/src/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/stuart/src/scuttlebot/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/stuart/src/scuttlebot/node_modules/pull-reader/index.js:39:14)
```
That traceback is from my scuttlebot instance.

**Comment by evbogue** [comment]
@sdgathman hmm... I haven't seen this error before.

Are you running sbot using `npm start` in the minbay folder, or are you using a separate scuttlebot instance?

Is your `localstorage.remote` in the browser the same as `sbot ws.getAddress` on your command line?

Any other information you can give me will help!

**Comment by evbogue** [comment]
Replied on ssb: http://evbogue.com:8807/%vKaTMp4S0Bf/uA/lVRsoBstutkF8VEpG9apfqwA9KZw=.sha256

**Comment by evbogue** [comment]
I don't think we ever figured out what went wrong here, but I don't think we'll get this same error now that Minbay has been reworked to depend on Patchless.
