### ISSUE TITLE
crash after startup on win7

### ISSUE THREAD

**Issue by severak** [evbogue/minbay#6]
Hi, just tested minbay on other PC. Issue #5 seems to be closed. Install and build seems to be OK, but `npm start` crashes after it opens browser window with minbay with no content at all.

Log:

```
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle minbay@3.2.0~prestart: minbay@3.2.0
6 info lifecycle minbay@3.2.0~start: minbay@3.2.0
7 verbose lifecycle minbay@3.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle minbay@3.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\severak\minbay\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\GitExtensions\;D:\bin\Go\bin;;D:\bin\tdmgcc\bin;C:\Program Files\nodejs\;D:\bin;D:\bin\php;C:\Users\Mímouš\AppData\Roaming\npm
9 verbose lifecycle minbay@3.2.0~start: CWD: D:\severak\minbay
10 silly lifecycle minbay@3.2.0~start: Args: [ '/d /s /c', 'node bin' ]
11 silly lifecycle minbay@3.2.0~start: Returned: code: 3221225725  signal: null
12 info lifecycle minbay@3.2.0~start: Failed to exec start script
13 verbose stack Error: minbay@3.2.0 start: `node bin`
13 verbose stack Exit status 3221225725
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid minbay@3.2.0
15 verbose cwd D:\severak\minbay
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 3221225725
22 error minbay@3.2.0 start: `node bin`
22 error Exit status 3221225725
23 error Failed at the minbay@3.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225725, true ]

```

**Comment by evbogue** [comment]
@severak A few questions:

+ Do your mean your browser crashes, or Node crashes? 
+ Is there any error in your browser console?
+ I'm not super familiar with windows. Is scuttlebot working on windows for you?

If you disable this line: https://github.com/evbogue/minbay/blob/master/bin.js#L74 does it work?

**Comment by evbogue** [comment]
@severak Reading this error, I think the key line might be `13 verbose stack Error: minbay@3.2.0 start: `node bin`

How do you launch node.js programs in windows? Maybe the start script isn't correct for the environment.

**Comment by evbogue** [comment]
@severak "after it opens browser window with minbay with no content at all." this is where I wonder if there is an error within your browser console. Do you see the navbar though? If you see the navbar, make sure to import your key from `.ssb/secret`

**Comment by severak** [comment]
Hi. It looks like this:

![screen shot 12-24-17 at 10 06 am](https://user-images.githubusercontent.com/615685/34325454-45ea25b4-e892-11e7-8cde-973642066f43.PNG)

There is some error in the console window of browser. There is also some error in nodejs cli.

Despite of errors, both browser javascript and cli javascript are alive, I can switch to key tabs for example.

---

Browser error:

~~~
Error: could not connect to sbot
[354]</</module.exports/<@http://localhost:3013/:32474:23
next@http://localhost:3013/:21486:14
next/<@http://localhost:3013/:21496:9
_cb@http://localhost:3013/:21811:20
secure/<@http://localhost:3013/:31098:22
once/<@http://localhost:3013/:26116:5
[259]</module.exports/writer<@http://localhost:3013/:26129:13
callback@http://localhost:3013/:26432:7
drain@http://localhost:3013/:26419:39
end@http://localhost:3013/:26386:5
abort@http://localhost:3013/:26138:9
abort@http://localhost:3013/:31019:33
  abort@http://localhost:3013/:31019:45
[337]</</module.exports/exports.createClientStream/</</<@http://localhost:3013/:31033:26
drain@http://localhost:3013/:26525:9
more/<@http://localhost:3013/:26542:18
maxDelay/</<@http://localhost:3013/:26503:7
map/</</<@http://localhost:3013/:25970:9
[309]</module.exports/<@http://localhost:3013/:27139:7
~~~

Cli log (incomplete):

~~~
OeEmLtElHF5kdFElyXDA==.sig.ed25519' } { local: { seq: 396, req: 396, tx: true },

  remote: { seq: 451, req: 454, tx: true },
  ready: null,
  effect: null,
  error: true }
WRONG MESSAGE { previous: '%Kb/eRKX/0hr4Ffzz5KdYKJjkCFT0st16kkEWRxaAHr4=.sha256'
,
  author: '@IgYpd+tCtXnlE2tYX/8rR2AGt+P8svC98WH3MdYAa8Y=.ed25519',
  sequence: 452,
  timestamp: 1513824057113,
  hash: 'sha256',
  content:
   { type: 'vote',
     channel: 'anarchism',
     vote:
      { link: '%s378+4DtxUwyUP6xOZAQeVq1YucsegxLN9Rze/0cPaY=.sha256',
        value: 1,
        expression: 'Like' } },
  signature: 'hFSbBiylL+kC62kctVwLH+8K4xGlO48WDaLfFXlojI8oXdmIx4e94euer6t4Z68/Bj
3fpNl8jKPgWptAYCSUBA==.sig.ed25519' } { local: { seq: 396, req: 396, tx: true },

  remote: { seq: 452, req: 454, tx: true },
  ready: null,
  effect: null,
  error: true }
WRONG MESSAGE { previous: '%871FAV4y6VVKSxlOlgvPrvG9H22CMeTmCgC0bIbXRps=.sha256'
,
  author: '@IgYpd+tCtXnlE2tYX/8rR2AGt+P8svC98WH3MdYAa8Y=.ed25519',
  sequence: 453,
  timestamp: 1513947062027,
  hash: 'sha256',
  content:
   { type: 'vote',
     channel: 'metalwork',
     vote:
      { link: '%McCOGp/ewl8+NC9eKoN3JC9g8T06+fMRarPWPiJ/Ud4=.sha256',
        value: 1,
        expression: 'Like' } },
  signature: '11UsW7UZr4sazQBEZmXi7xutbGd24Fl3bv8+/mGmdVRBI5k2aC2ZK4C8R5ojyYUVSO
nmaJB0OSGMpfdI82JTDA==.sig.ed25519' } { local: { seq: 396, req: 396, tx: true },

  remote: { seq: 453, req: 454, tx: true },
  ready: null,
  effect: null,
  error: true }
WRONG MESSAGE { previous: '%t4hqEBRMZX9Gz3iq7noYXDhxE++zDCpJ2lzp8QHdmZQ=.sha256'
,
  author: '@IgYpd+tCtXnlE2tYX/8rR2AGt+P8svC98WH3MdYAa8Y=.ed25519',
  sequence: 454,
  timestamp: 1513947132024,
  hash: 'sha256',
  content:
   { type: 'vote',
     vote:
      { link: '%IscLnXdESiiRZ7BZ4p0GYSR3xugzFf8B/nDe7nhNp1M=.sha256',
        value: 1,
        expression: 'Like' } },
  signature: 'SNW1ejXy2BV7pZQqWCd40qi/DjNhkLIciGBS1Bw0lVnoSg/jLKkHp+6hGWdVnPkbzP
k2GcCzVn3Z4jm/lY76AQ==.sig.ed25519' } { local: { seq: 396, req: 396, tx: true },

  remote: { seq: 454, req: 454, tx: true },
  ready: null,
  effect: null,
  error: true }
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:75:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
server error, from
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:76:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
Error: client unauthorized
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:97:44
    at D:\severak\minbay\node_modules\ssb-ws\index.js:73:12
    at D:\severak\minbay\node_modules\ssb-friends\index.js:215:9
    at get (D:\severak\minbay\node_modules\flumeview-reduce\inject.js:115:11)
    at D:\severak\minbay\node_modules\flumedb\wrap.js:45:11
    at ready (D:\severak\minbay\node_modules\flumedb\wrap.js:24:80)
    at Object.get (D:\severak\minbay\node_modules\flumedb\wrap.js:44:9)
    at Object.get (D:\severak\minbay\node_modules\ssb-friends\index.js:200:13)
    at Object.hooked [as get] (D:\severak\minbay\node_modules\hoox\index.js:10:1
5)
    at _auth (D:\severak\minbay\node_modules\ssb-ws\index.js:70:18)
CONNECT { host: 'ssb.ekata.social',
  port: 8008,
  key: '@FJDMuATvh0a3qIcIPcstUANVIj362fWkYCG5bnkZ5nA=.ed25519',
  source: 'stored',
  announcers: 22,
  duration:
   { mean: 7916.6,
     stdev: 20639.296287422207,
     count: 10,
     sum: 79166,
     sqsum: 4886531068 },
  stateChange: 1514106228468,
  client: true,
  ping:
   { rtt: { mean: 1492, stdev: 0, count: 1, sum: 1492, sqsum: 2226064 },
     skew: { mean: -1530, stdev: 0, count: 1, sum: -1530, sqsum: 2340900 } },
  failure: 0,
  state: undefined,
  disconnect: [Function] }
Connected ssb.ekata.social:8008:@FJDMuATvh0a3qIcIPcstUANVIj362fWkYCG5bnkZ5nA=.ed
25519
EBT failed, fallback to legacy { message: 'method:ebt,replicate is not on whitel
ist',
  name: 'Error',
  stack: 'Error: method:ebt,replicate is not on whitelist\n    at Function.perms
.pre (/usr/src/app/node_modules/muxrpc/permissions.js:88:14)\n    at Object.<ano
nymous> (/usr/src/app/node_modules/muxrpc/local-api.js:35:21)\n    at PacketStre
amSubstream.stream.read (/usr/src/app/node_modules/muxrpc/stream.js:67:23)\n
at PacketStream._onstream (/usr/src/app/node_modules/packet-stream/index.js:230:
11)\n    at PacketStream.write (/usr/src/app/node_modules/packet-stream/index.js
:135:41)\n    at /usr/src/app/node_modules/muxrpc/pull-weird.js:56:15\n    at /u
sr/src/app/node_modules/pull-stream/sinks/drain.js:24:37\n    at /usr/src/app/no
de_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11\n    a
t Object.cb (/usr/src/app/node_modules/packet-stream-codec/index.js:107:11)\n
 at drain (/usr/src/app/node_modules/pull-reader/index.js:39:14)' }
replication ended: @FJDMuATvh0a3qIcIPcstUANVIj362fWkYCG5bnkZ5nA=.ed25519 Error:
method:ebt,replicate is not on whitelist
    at Function.perms.pre (/usr/src/app/node_modules/muxrpc/permissions.js:88:14
)
    at Object.<anonymous> (/usr/src/app/node_modules/muxrpc/local-api.js:35:21)
    at PacketStreamSubstream.stream.read (/usr/src/app/node_modules/muxrpc/strea
m.js:67:23)
    at PacketStream._onstream (/usr/src/app/node_modules/packet-stream/index.js:
230:11)
    at PacketStream.write (/usr/src/app/node_modules/packet-stream/index.js:135:
41)
    at /usr/src/app/node_modules/muxrpc/pull-weird.js:56:15
    at /usr/src/app/node_modules/pull-stream/sinks/drain.js:24:37
    at /usr/src/app/node_modules/pull-goodbye/node_modules/pull-stream/throughs/
filter.js:17:11
    at Object.cb (/usr/src/app/node_modules/packet-stream-codec/index.js:107:11)

    at drain (/usr/src/app/node_modules/pull-reader/index.js:39:14)
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:75:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
server error, from
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:76:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
Error: client unauthorized
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:97:44
    at D:\severak\minbay\node_modules\ssb-ws\index.js:73:12
    at D:\severak\minbay\node_modules\ssb-friends\index.js:215:9
    at get (D:\severak\minbay\node_modules\flumeview-reduce\inject.js:115:11)
    at D:\severak\minbay\node_modules\flumedb\wrap.js:45:11
    at ready (D:\severak\minbay\node_modules\flumedb\wrap.js:24:80)
    at Object.get (D:\severak\minbay\node_modules\flumedb\wrap.js:44:9)
    at Object.get (D:\severak\minbay\node_modules\ssb-friends\index.js:200:13)
    at Object.hooked [as get] (D:\severak\minbay\node_modules\hoox\index.js:10:1
5)
    at _auth (D:\severak\minbay\node_modules\ssb-ws\index.js:70:18)
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:75:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
server error, from
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:76:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
Error: client unauthorized
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:97:44
    at D:\severak\minbay\node_modules\ssb-ws\index.js:73:12
    at D:\severak\minbay\node_modules\ssb-friends\index.js:215:9
    at get (D:\severak\minbay\node_modules\flumeview-reduce\inject.js:115:11)
    at D:\severak\minbay\node_modules\flumedb\wrap.js:45:11
    at ready (D:\severak\minbay\node_modules\flumedb\wrap.js:24:80)
    at Object.get (D:\severak\minbay\node_modules\flumedb\wrap.js:44:9)
    at Object.get (D:\severak\minbay\node_modules\ssb-friends\index.js:200:13)
    at Object.hooked [as get] (D:\severak\minbay\node_modules\hoox\index.js:10:1
5)
    at _auth (D:\severak\minbay\node_modules\ssb-ws\index.js:70:18)
CONNECT { host: 'ssb.interweb.technology',
  port: 8008,
  key: '@CQSMJsDjpn5t59MXqMp1q3JJ3+19K9Jn0Z3LQfZkVBI=.ed25519',
  source: 'stored',
  announcers: 16,
  duration: { mean: 0, stdev: 0, count: 3, sum: 0, sqsum: 0 },
  stateChange: 1513552408248,
  error: 'Error: connect ECONNREFUSED 209.177.93.42:8008\n    at Object._errnoEx
ception (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)',
  failure: 3 }
CONNECT { host: '198.211.122.115',
  port: 8008,
  key: '@7snGJQdhw12HrUTzeaWMfxuBO8c2U75sG7sNkeEfYOw=.ed25519',
  source: 'stored',
  announcers: 173,
  duration: { mean: 0, stdev: 0, count: 3, sum: 0, sqsum: 0 },
  stateChange: 1513552427467,
  error: 'Error: connect ETIMEDOUT 198.211.122.115:8008\n    at Object._errnoExc
eption (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    a
t TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)',
  failure: 3 }
CONNECT { host: '174.138.95.192',
  port: 8008,
  key: '@CLByOVQdEzqurF2EMHVhkBv5h3SH8mAEhXbu3jqZB2I=.ed25519',
  source: 'stored',
  announcers: 29,
  duration: { mean: 0, stdev: 0, count: 3, sum: 0, sqsum: 0 },
  stateChange: 1513552427467,
  error: 'Error: connect ETIMEDOUT 174.138.95.192:8008\n    at Object._errnoExce
ption (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at
 TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)',
  failure: 3 }
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:75:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
server error, from
Error: ---------------
    at Console.console.error (D:\severak\minbay\node_modules\ssb-ooo\index.js:18
:7)
    at onError (D:\severak\minbay\node_modules\multiserver\compose.js:76:17)
    at D:\severak\minbay\node_modules\multiserver\compose.js:83:21
    at next (D:\severak\minbay\node_modules\multiserver\compose.js:24:14)
    at D:\severak\minbay\node_modules\multiserver\compose.js:34:9
    at _cb (D:\severak\minbay\node_modules\multiserver\plugins\shs.js:28:20)
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:115:22
    at D:\severak\minbay\node_modules\pull-handshake\index.js:10:5
    at D:\severak\minbay\node_modules\pull-handshake\index.js:23:13
    at callback (D:\severak\minbay\node_modules\pull-pushable\index.js:82:7)
Error: client unauthorized
    at D:\severak\minbay\node_modules\secret-handshake\protocol.js:97:44
    at D:\severak\minbay\node_modules\ssb-ws\index.js:73:12
    at D:\severak\minbay\node_modules\ssb-friends\index.js:215:9
    at get (D:\severak\minbay\node_modules\flumeview-reduce\inject.js:115:11)
    at D:\severak\minbay\node_modules\flumedb\wrap.js:45:11
    at ready (D:\severak\minbay\node_modules\flumedb\wrap.js:24:80)
    at Object.get (D:\severak\minbay\node_modules\flumedb\wrap.js:44:9)
    at Object.get (D:\severak\minbay\node_modules\ssb-friends\index.js:200:13)
    at Object.hooked [as get] (D:\severak\minbay\node_modules\hoox\index.js:10:1
5)
    at _auth (D:\severak\minbay\node_modules\ssb-ws\index.js:70:18)
~~~

**Comment by evbogue** [comment]
@severak My hunch is the key in your browser isn't friends with your local pub. 

This is a user interface error. Minbay should prompt you to import your key, or give you a lite client invite, if you are not friends with the local pub. 

Try importing your key from `.ssb/secret` into the `#key` tab in Minbay. To solve this error, right now, they need to be the same key in both locations so that websocket authentication works.

**Comment by evbogue** [comment]
@severak Are you still getting this error in the latest minbay?

**Comment by severak** [comment]
After reinstall and manual import it seems to be working. It's showing my content as seen in patchwork before.

**Comment by evbogue** [comment]
@severak Awesome. I'll go ahead and close this issue!
