### ISSUE TITLE
runaway blobs

### ISSUE THREAD

**Issue by evbogue** [evbogue/minbay#7]
Sometimes minbay begins to load every blob known to man and doesn't stop until my computer crashes. I'm not sure if this is a minbay or a patchless issue. 

I'm going to attempt to reproduce in Patchless.

I also tried backing up to the last stable release of scuttlebot@10.4.10

**Comment by evbogue** [comment]
Got an error! Nice.

```
/blobs/get/&KNZJzRgYHr7YZcpsm/PzcJ4N5YD7CIqaJYdK/fFUpz0=.sha256 s/get/&KNZJzRgYHr7YZcpsm/PzcJ4N5YD7CIqaJYdK/fFUpz0=.sha256
/blobs/get/&oneOil9RCidzBjRZiIE0OVxAAQUZPBxCyNhYejYzLVA=.sha256 s/get/&oneOil9RCidzBjRZiIE0OVxAAQUZPBxCyNhYejYzLVA=.sha256
/blobs/get/&6vYJz8vJ0zBZetCBwzPd1naXbAb7iEuCcKhCDcnBB4M=.sha256 s/get/&6vYJz8vJ0zBZetCBwzPd1naXbAb7iEuCcKhCDcnBB4M=.sha256
/blobs/get/&bmieIJTW7B0xWDqTy+etRc+BeSsWXa2bptfatEU60aM=.sha256 s/get/&bmieIJTW7B0xWDqTy+etRc+BeSsWXa2bptfatEU60aM=.sha256
/blobs/get/&cmULZpffgIb+Osfes48GAqj8W1tU4PZgn8wmiM/9vIs=.sha256 s/get/&cmULZpffgIb+Osfes48GAqj8W1tU4PZgn8wmiM/9vIs=.sha256
/blobs/get/&6LUCUBRdSGcs/4kPsOVy2JdUgSSFC+gOGTQfPFBDCSM=.sha256 s/get/&6LUCUBRdSGcs/4kPsOVy2JdUgSSFC+gOGTQfPFBDCSM=.sha256
/blobs/get/&cqp0rEzuKFPxG+C7ESyB6RnCbE0DAYI86/fKd66DYUk=.sha256 s/get/&cqp0rEzuKFPxG+C7ESyB6RnCbE0DAYI86/fKd66DYUk=.sha256
/blobs/get/&KZ3EPdneevMmXifBwy1q1ykx+Cxpcqu01Uwu6qcckmo=.sha256 s/get/&KZ3EPdneevMmXifBwy1q1ykx+Cxpcqu01Uwu6qcckmo=.sha256
/blobs/get/&gek33qo+avgwSBIQ0IyQ4+Ft5cl+WVXKPmyRzEbjwyQ=.sha256 s/get/&gek33qo+avgwSBIQ0IyQ4+Ft5cl+WVXKPmyRzEbjwyQ=.sha256
/blobs/get/&HLFdrrWw/qMegVVgRIaKKN1JQjvAWsxHHPfVXEsTYG4=.sha256 s/get/&HLFdrrWw/qMegVVgRIaKKN1JQjvAWsxHHPfVXEsTYG4=.sha256
/blobs/get/&mwzoWJrKPhcrr4g3dPBVp3EBEiyMeCSHgxsanIWefIc=.sha256 s/get/&mwzoWJrKPhcrr4g3dPBVp3EBEiyMeCSHgxsanIWefIc=.sha256
/blobs/get/&ofWwaWDtzWPLCGlvETmXT8fe2PJEyAYjRUw47zjXBIM=.sha256 s/get/&ofWwaWDtzWPLCGlvETmXT8fe2PJEyAYjRUw47zjXBIM=.sha256
/blobs/get/&6cEWJllhx8Fq3X0zCJGQjOwcNT+Jrq3kwapOtXJj4zo=.sha256 s/get/&6cEWJllhx8Fq3X0zCJGQjOwcNT+Jrq3kwapOtXJj4zo=.sha256
/blobs/get/&bJwjV84TerogwirlQH9JB9+bEgROqlDo8ipAl3IoN5g=.sha256 s/get/&bJwjV84TerogwirlQH9JB9+bEgROqlDo8ipAl3IoN5g=.sha256
/blobs/get/&W3Cf3DWLPuFXhGdXvU6tjuo4QcXwkvUWPfR53vwtj2M=.sha256 s/get/&W3Cf3DWLPuFXhGdXvU6tjuo4QcXwkvUWPfR53vwtj2M=.sha256
/blobs/get/&fxVJsGQ56bpHymNKXSMGhWFRA4GSGiw1U10VARfV6C4=.sha256 s/get/&fxVJsGQ56bpHymNKXSMGhWFRA4GSGiw1U10VARfV6C4=.sha256
/blobs/get/&P/2oYciViJNBH4H3a6PQr2JmZQ1/jOrmhiVxn9E3A1M=.sha256 s/get/&P/2oYciViJNBH4H3a6PQr2JmZQ1/jOrmhiVxn9E3A1M=.sha256
/blobs/get/&4nGtB51noatUWBVAwzjHyEU72xgT7wHEGZ+dzSNre8M=.sha256 s/get/&4nGtB51noatUWBVAwzjHyEU72xgT7wHEGZ+dzSNre8M=.sha256
/blobs/get/&lk3Ep1PvyaGQGdVQGHIV5KIyqEnZs2UZwpKug9wf0vw=.sha256 s/get/&lk3Ep1PvyaGQGdVQGHIV5KIyqEnZs2UZwpKug9wf0vw=.sha256
/home/ev/minbay/node_modules/flumelog-offset/inject.js:80
        else cb(null, codec.decode(value))
                            ^

RangeError: Maximum call stack size exceeded
    at Object.parse [as decode] (<anonymous>)
    at /home/ev/minbay/node_modules/flumelog-offset/inject.js:80:29
    at /home/ev/minbay/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/ev/minbay/node_modules/aligned-block-file/blocks.js:72:11
    at get (/home/ev/minbay/node_modules/aligned-block-file/blocks.js:28:7)
    at next (/home/ev/minbay/node_modules/aligned-block-file/blocks.js:51:7)
    at Object.read (/home/ev/minbay/node_modules/aligned-block-file/blocks.js:75:7)
    at next (/home/ev/minbay/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /home/ev/minbay/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /home/ev/minbay/node_modules/aligned-block-file/blocks.js:93:11
npm info lifecycle minbay@3.4.0~start: Failed to exec start script
```

**Comment by evbogue** [comment]
Have you ever seen this in Patchless @dominictarr?

**Comment by evbogue** [comment]
I'm unable to immediately replicate this issue in Patchless, so I think it's an error in the way I'm handling hyperscroll within Minbay. I'll see if I can isolate this after work tomorrow.

**Comment by evbogue** [comment]
Also scrolling has become a lot slower in Minbay than it is in Patchless. This might be related?

**Comment by dominictarr** [comment]
that is weird.
there are clues:
* are those blobs avatars? (this is my hunch)
* when did scrolling become slow? what commit?

I tried to reproduce this in minbay and I think I saw it, but not sure how to make it happen.

**Comment by dominictarr** [comment]
yeah it looks like these are avatars

**Comment by dominictarr** [comment]
pretty sure that what is happening is some view that is not currently displayed is thinking that it's scrolling into view, and keeps on adding elements, probably essentially doing a full scan of the database adding every avatar

**Comment by dominictarr** [comment]
I think I got a reproduction:
first run `top` in terminal next to sbot, so you can monitor memory used.
open some popular channels, such as #solarpunk _and then close them again_, then watch blobs log and memory use climb.

**Comment by dominictarr** [comment]
the fix, I think is to make sure that hyperloadmore/stream needs to detect if it's content element is no longer in the DOM and abort the streams: https://github.com/dominictarr/hyperloadmore/blob/master/stream.js

**Comment by evbogue** [comment]
I haven't quite been able to replicate this reliably yet, but it makes sense that it'd be the channels view. 

One thought: Is this _just_ the channels view, and if so what is different about the channels view than the public view?

**Comment by dominictarr** [comment]
the is the right question to be asking! https://github.com/dominictarr/patchapp-threads/blob/master/channels.js#L29-L35

channel view is just a filter on the main log. that means could read a lot of data. If it's still looking for enough channel messages to fill the screen, it's gonna read every message in the log.

**Comment by evbogue** [comment]
@dominictarr I was able to reproduce this by creating this post: `%FI0vCaMItg3ZUOdQJWLxLU95dPh112WW/AH/t7WoJj4=.sha256` which has a channel that only has one message. Loading the channel gives me consistent runaway blobs.

You can also sometimes reproduce this by scrolling through the public feed, as channels are loaded on messages as well.

However, I'm only getting the runaway blobs error in minbay. Patchless works fine for me. Were you able to reproduce this error in Patchless? If not then this bug is only in minbay or maybe `patchnav-less`?

**Comment by evbogue** [comment]
Confirmed. This is just a minbay issue. `patchnav-less` in the Patchless Electron/lite doesn't have the same issue.
